### ISSUE TITLE
docker: Error response from daemon: Could not get container for mongodb.

### ISSUE THREAD

**Issue by ghost** [TeamHG-Memex/sitehound-frontend#7]
This may be a *very* noob mistake, but I couldn't find useful prior cases to learn from.

The official repo is `mongo`, not `mongodb`, but running the docker command with `--link mongo:latest` doesn't help.

**Comment by fornarat** [comment]
Didn't the custom mongo docker image we provide work for you?

**Comment by fornarat** [comment]
There is a new docker-compose + docs for the installation

**Comment by ghost** [comment]
Thank you! Sorry for silence on prior question - have been slammed. Short version: I didn't know what image you meant. Will be glad to play with this, now! :)

On 22 June 2017 18:52:47 CEST, Tomas Fornara <notifications@github.com> wrote:
>There is a new docker-compose + docs for the installation
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TeamHG-Memex/sitehound/issues/7#issuecomment-310438898

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
